site_name = "wgt"
base_path = "/wg-tui"
footer_text = "© [oddship](https://github.com/oddship) 2026"

[[topnav]]
title = "Changelog"
url = "/changelog/"

[[topnav]]
title = "GitHub"
url = "https://github.com/oddship/wg-tui"
icon = "github"

[feed]
enabled = true
link = "https://oddship.github.io/wg-tui"

[extra]
tagline = "Warpgate target picker for the terminal"
